// posts.js
export const posts = [
  {
    id: 1,
    image: '',
    title: 'Counting Stars with Numbers ✨',
    hashtags: [
      '#Class1',
      '#MathsFun',
      '#BasicCounting',
      '#KidsLearning',
      '#EducationMatters',
    ],
    description:
      'Class 1 students begin their journey with numbers! Counting fruits, stars, and more makes maths fun and visual.',
    username: 'learn_with_love',
    userphoto: '',
    likes: 120,
    comments: 5,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 2,
    image: '',
    title: 'Living and Non-Living World 🌱🔧',
    hashtags: [
      '#Class2',
      '#ScienceBasics',
      '#NatureLover',
      '#EarlyScience',
      '#LearningWithNature',
    ],
    description:
      'Teaching children the difference between living and non-living things using real-life examples like pets, plants, and toys.',
    username: 'young_explorer',
    userphoto: '',
    likes: 89,
    comments: 6,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 3,
    image: '',
    title: 'Shapes Are Everywhere 🔺⚫',
    hashtags: [
      '#MathsIsFun',
      '#GeometryBasics',
      '#Class3',
      '#VisualLearning',
      '#SmartKids',
    ],
    description:
      'From circles in wheels to rectangles in books, Class 3 students discover shapes in the world around them.',
    username: 'maths_magic',
    userphoto: '',
    likes: 145,
    comments: 10,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 4,
    image: '',
    title: 'Water Cycle Wonder 💧☁️🌧️',
    hashtags: [
      '#Class4',
      '#ScienceExperiment',
      '#WaterCycle',
      '#LearningThroughDiagrams',
      '#EduIndia',
    ],
    description:
      'Exploring the stages of the water cycle—evaporation, condensation, and precipitation—using hands-on charts and experiments.',
    username: 'h2o_journey',
    userphoto: '',
    likes: 200,
    comments: 15,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 5,
    image: '',
    title: 'Multiplication Table Tricks ✖️🧠',
    hashtags: [
      '#Class5',
      '#QuickMaths',
      '#MathTricks',
      '#MultiplicationMastery',
      '#BrainWorkout',
    ],
    description:
      'Students master multiplication tables up to 20 using Vedic math techniques and visual memorization games.',
    username: 'maths_champ',
    userphoto: '',
    likes: 300,
    comments: 25,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 6,
    image: '',
    title: 'Electric Circuits Made Easy ⚡🔋',
    hashtags: [
      '#Class6',
      '#BasicPhysics',
      '#Electricity',
      '#ScienceLab',
      '#HandsOnLearning',
    ],
    description:
      'Class 6 kids build simple circuits using batteries and bulbs, understanding the concept of current flow in a practical way.',
    username: 'young_physicist',
    userphoto: '',
    likes: 410,
    comments: 32,
    time: '4 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 7,
    image: '',
    title: 'Nutrition in Food 🍎🍚🥦',
    hashtags: [
      '#ScienceClass',
      '#NutritionAwareness',
      '#Class7',
      '#HealthyLiving',
      '#FoodScience',
    ],
    description:
      'Learning how carbohydrates, proteins, and fats work in our body, and how to balance our diet every day.',
    username: 'food_science_fun',
    userphoto: '',
    likes: 275,
    comments: 18,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 8,
    image: '',
    title: 'Understanding Rational Numbers ➗',
    hashtags: [
      '#Class7',
      '#RationalNumbers',
      '#MathConcepts',
      '#NCERTMaths',
      '#StudySmart',
    ],
    description:
      'Class 7 students dive into rational numbers—fractions, negative numbers, and number lines—building a strong base for algebra.',
    username: 'maths_mastery',
    userphoto: '',
    likes: 160,
    comments: 8,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 9,
    image: '',
    title: 'Laws of Motion Unleashed 🏃‍♂️🔬',
    hashtags: [
      '#Class8',
      '#PhysicsBasics',
      '#NewtonLaws',
      '#ScienceIsFun',
      '#StudentScience',
    ],
    description:
      'Exploring Newton’s three laws of motion with practical examples like cycling, skating, and jumping. Let the experiments begin!',
    username: 'motion_mentor',
    userphoto: '',
    likes: 500,
    comments: 44,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 10,
    image: '',
    title: 'Algebra Adventures 📘🧮',
    hashtags: [
      '#Class8',
      '#AlgebraRules',
      '#MathExpressions',
      '#SolveWithFun',
      '#IndianEducation',
    ],
    description:
      'From unknowns to equations, students start solving algebraic expressions step by step with real-life problem scenarios.',
    username: 'x_y_solver',
    userphoto: '',
    likes: 372,
    comments: 28,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 11,
    image: '',
    title: 'Periodic Table Rap 🧪🎤',
    hashtags: [
      '#Class9',
      '#ChemistryFun',
      '#PeriodicTable',
      '#MnemonicMagic',
      '#ScienceLearning',
    ],
    description:
      'Students memorize periodic table elements using catchy songs and rhymes. Who said chemistry is boring?',
    username: 'chembeats',
    userphoto: '',
    likes: 610,
    comments: 35,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 12,
    image: '',
    title: 'Real Numbers & Root Magic ✨',
    hashtags: [
      '#Class10',
      '#RealNumbers',
      '#MathBoardPrep',
      '#CBSEMaths',
      '#StudyMotivation',
    ],
    description:
      'Class 10 students master Euclid’s Division Lemma and square roots to prepare for board exams with confidence and clarity.',
    username: 'board_ready',
    userphoto: '',
    likes: 580,
    comments: 42,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
    {
    id: 13,
    image: '',
    title: 'The Cell City 🧬🔬',
    hashtags: ['#Class9', '#BiologyBasics', '#CellStructure', '#ScienceLife', '#LearningBiology'],
    description: 'Class 9 students dive into the microscopic world. Understanding cell organelles by comparing them to parts of a city is a fun way to learn biology!',
    username: 'bio_guide',
    userphoto: '',
    likes: 440,
    comments: 22,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 14,
    image: '',
    title: 'Light – Reflection & Refraction 🔍💡',
    hashtags: ['#Class10', '#PhysicsConcepts', '#ReflectionRefraction', '#BoardPrep', '#NCERTPhysics'],
    description: 'Learn how light bends and bounces with easy mirror and lens experiments. Let’s make Physics visual and practical!',
    username: 'bright_concepts',
    userphoto: '',
    likes: 680,
    comments: 39,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 15,
    image: '',
    title: 'Mensuration Magic 📐🔢',
    hashtags: ['#Class9', '#MathFun', '#Mensuration', '#GeometryTools', '#PracticeMakesPerfect'],
    description: 'Understanding volume and surface area of cubes, cylinders, and cones through real-world object measurements.',
    username: 'maths_buddy',
    userphoto: '',
    likes: 352,
    comments: 16,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 16,
    image: '',
    title: 'Power of Exponents 🔢💥',
    hashtags: ['#Class8', '#MathConcepts', '#ExponentsRules', '#SimplifyMaths', '#SmartStudents'],
    description: 'From squaring numbers to large scientific notations, exponents make calculations simpler and faster!',
    username: 'classroom_x',
    userphoto: '',
    likes: 240,
    comments: 11,
    time: '4 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 17,
    image: '',
    title: 'Understanding Force and Pressure 💪🧲',
    hashtags: ['#Class8', '#ForceAndPressure', '#PhysicsInDailyLife', '#NCERTPhysics', '#FunExperiments'],
    description: 'Explaining how rickshaws move and balloons burst—all with Newton’s magic!',
    username: 'force_master',
    userphoto: '',
    likes: 511,
    comments: 21,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 18,
    image: '',
    title: 'Decimals in Daily Life 💰📏',
    hashtags: ['#Class6', '#DecimalMath', '#MoneyMath', '#EasyMaths', '#ConceptBasedLearning'],
    description: 'Using money, meters, and grams to teach students how decimals are part of our daily life.',
    username: 'practical_maths',
    userphoto: '',
    likes: 138,
    comments: 6,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 19,
    image: '',
    title: 'The Nervous System Explained 🧠⚡',
    hashtags: ['#Class10', '#HumanBiology', '#NervousSystem', '#ScienceAwareness', '#CBSEScience'],
    description: 'Understanding how our body reacts in a flash, thanks to nerves, spinal cord and the brain!',
    username: 'mind_connections',
    userphoto: '',
    likes: 620,
    comments: 34,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 20,
    image: '',
    title: 'Understanding Algebraic Identities ✍️📘',
    hashtags: ['#Class9', '#AlgebraRules', '#MathTips', '#ExamPreparation', '#FormulaMastery'],
    description: 'a² + b² + 2ab? No more confusion! We break down the identities with logic and colorful examples.',
    username: 'formula_freak',
    userphoto: '',
    likes: 429,
    comments: 19,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 21,
    image: '',
    title: 'Plant Kingdom 🌿🔍',
    hashtags: ['#Class11', '#BiologyBotany', '#NCERTBiology', '#PlantDiversity', '#ScienceClass'],
    description: 'From algae to gymnosperms, students of Class 11 explore the diversity and classification of the plant world with visual flowcharts.',
    username: 'plant_log',
    userphoto: '',
    likes: 301,
    comments: 20,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 22,
    image: '',
    title: 'Straight Lines, Infinite Ideas ➕➖',
    hashtags: ['#Class11', '#CoordinateGeometry', '#StraightLines', '#MathConcepts', '#Learn2Grow'],
    description: 'Mid-points, slopes, and perpendicularity explained with graphs. Geometry becomes powerful when drawn!',
    username: 'geometry_geek',
    userphoto: '',
    likes: 487,
    comments: 25,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 23,
    image: '',
    title: 'Thermodynamics in Real Life 🔥❄️',
    hashtags: ['#Class11', '#PhysicsPower', '#Thermodynamics', '#NCERTPhysics', '#HeatTransfer'],
    description: 'Learn how your fridge works, how heaters warm up rooms, and how engines convert fuel into motion using the laws of thermodynamics.',
    username: 'realphysics',
    userphoto: '',
    likes: 710,
    comments: 44,
    time: '4 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 24,
    image: '',
    title: 'Derivatives – A Beginner’s Launchpad 📈📐',
    hashtags: ['#Class12', '#Calculus', '#Derivatives', '#MathIsLife', '#CBSEBoard'],
    description: 'Understanding the rate of change and slope of a curve, Class 12 students enter the powerful world of calculus.',
    username: 'calc_path',
    userphoto: '',
    likes: 609,
    comments: 36,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 25,
    image: '',
    title: 'Electrostatics: Charges & Fields ⚡🧲',
    hashtags: ['#Class12', '#Electrostatics', '#BoardPhysics', '#JEEPrep', '#ConceptsMatter'],
    description: 'Why do combs attract paper? Why do you get shocks sometimes? Welcome to the world of electrostatics and electric fields!',
    username: 'electric_engage',
    userphoto: '',
    likes: 842,
    comments: 51,
    time: '1 hour ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 26,
    image: '',
    title: 'Organic Chemistry – Naming Game 🧪🔤',
    hashtags: ['#Class12', '#IUPACNaming', '#OrganicChemistry', '#BoardChemistry', '#ScienceLovers'],
    description: 'From methane to 2-bromo-3-methylpentane, students decode complex names into simple structures.',
    username: 'carbon_king',
    userphoto: '',
    likes: 389,
    comments: 29,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 27,
    image: '',
    title: 'Trigonometry in Action! 🔺📏',
    hashtags: ['#Class10', '#Trigonometry', '#RealWorldMath', '#SinCosTan', '#BoardExamPrep'],
    description: 'Measure the height of a tree or a building with just your eyes and angles. That’s the power of Trigonometry!',
    username: 'tri_guru',
    userphoto: '',
    likes: 570,
    comments: 32,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 28,
    image: '',
    title: 'Probability for Beginners 🎲📊',
    hashtags: ['#Class11', '#Probability', '#CBSEMath', '#BoardPreparation', '#ThinkSmart'],
    description: 'From tossing coins to predicting outcomes, probability builds your logical reasoning skills!',
    username: 'chance_cracker',
    userphoto: '',
    likes: 488,
    comments: 27,
    time: '3 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 29,
    image: '',
    title: 'DNA – The Blueprint of Life 🧬📚',
    hashtags: ['#Class12', '#Genetics', '#DNAExplained', '#HumanBiology', '#NEETPrep'],
    description: 'Discover how DNA holds the instructions to build and run living organisms. Explore genes, chromosomes, and heredity!',
    username: 'gene_journey',
    userphoto: '',
    likes: 654,
    comments: 38,
    time: '2 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
  },
  {
    id: 30,
    image: '',
    title: 'Board Exam Hacks & Strategy 💯📓',
    hashtags: ['#CBSE2025', '#Class10Tips', '#Class12Prep', '#BoardExams', '#StudyMotivation'],
    description: 'Final revision strategy, best timetable hacks, and question paper-solving tricks for Classes 10 & 12 students. Time to focus and conquer!',
    username: 'study_with_strategy',
    userphoto: '',
    likes: 1200,
    comments: 90,
    time: '5 hours ago',
    isLiked: false,
    isSaved: false,
    isFollowed: false,
      }
  

]
