export const dummyPosts = [
  {
    id: 1,
    username: 'alice',
    avatar: '/placeholder.png',
    images: '/placeholder.png', // single image
    likes: 150,
    caption: 'Enjoying the sunny day!',
    hashtags: ['sunshine', 'happy', 'weekend'],
    time: '2h ago',
  },
  {
    id: 2,
    username: 'bob',
    avatar: '/placeholder.png',
    images: ['/placeholder.png', '/placeholder.png', '/placeholder.png'], // multiple images
    likes: 230,
    caption: 'My recent trip photos',
    hashtags: ['travel', 'vacation', 'fun'],
    time: '1d ago',
  },
  {
    id: 3,
    username: 'charlie',
    avatar: '/placeholder.png',
    images: '/placeholder.png',
    likes: 45,
    caption: 'Trying out new recipes!',
    hashtags: ['foodie', 'cooking', 'yum'],
    time: '3h ago',
  },
  {
    id: 4,
    username: 'diana',
    avatar: '/placeholder.png',
    images: ['/placeholder.png', '/placeholder.png'], // multiple images
    likes: 120,
    caption: 'Weekend vibes with friends',
    hashtags: ['friends', 'party', 'weekendfun'],
    time: '5h ago',
  },
  {
    id: 5,
    username: 'edward',
    avatar: '/placeholder.png',
    images: '/placeholder.png',
    likes: 85,
    caption: 'Book reading session',
    hashtags: ['books', 'reading', 'relax'],
    time: '12h ago',
  },
  {
    id: 6,
    username: 'fiona',
    avatar: '/placeholder.png',
    images: [
      '/placeholder.png',
      '/placeholder.png',
      '/placeholder.png',
      '/placeholder.png',
    ],
    likes: 305,
    caption: 'Nature hike highlights',
    hashtags: ['nature', 'hiking', 'adventure'],
    time: '2d ago',
  },
  {
    id: 7,
    username: 'george',
    avatar: '/placeholder.png',
    images: '/placeholder.png',
    likes: 65,
    caption: 'Sunday brunch!',
    hashtags: ['food', 'brunch', 'sunday'],
    time: '4h ago',
  },
  {
    id: 8,
    username: 'hannah',
    avatar: '/placeholder.png',
    images: ['/placeholder.png', '/placeholder.png'],
    likes: 90,
    caption: 'City lights at night',
    hashtags: ['city', 'nightlife', 'photography'],
    time: '8h ago',
  },
]

export const followedUsersDummy = ['alice', 'charlie', 'edward', 'hannah']
